sudo: false
dist: trusty
language: java
jdk:
  - openjdk8
  - oraclejdk8
  - openjdk9
  - openjdk10
  - openjdk11
before_install:
  - ulimit -c unlimited -S
  - mvn -N io.takari:maven:wrapper
after_success:
  - bash .travis_after_success.sh
cache:
  directories:
    - $HOME/.m2

env:
  global:
    # CI_DEPLOY_USERNAME
    - secure: "dFeIAk6zsQdcDwC4r0gO4EOE7rgN2WjkIe2Me/5JIzvCmAK5R+aGvHUnOwMfqd/0W52vuidNMyVv7IjrsPsMmRIepquOskZbCCNLj2mfrS7M74Ou+mYaGiLIW5yhRBe5fMti3wyuy8bBf7k/o0IyUuhc5sbkLdHGBKAm58Y5XaX1uYUvA1VbxY60FqsdCFagi1GlQX4qTnCIyn7HXFtmzTJk4LT39lh6kvxKXuTyYD/zMcHi7BqWHDdOz0GBLyO9dhDfFBSjtbUuKyKcdgIDLU4HPgzL3yWUzYP5ExV+WG61fcxpv+y7cmlbNnS42ul8iiQeRDhetbJyWq4YLiBRwrQaYUwtWvUiokDMaDCrQDQjqYf9QJcaQHNIIXrvSfWM3//lRL7EaAyQTZ+ZbHSo+jSBPhJzASnVUhfw39uiWzhBAfx/ObYnofDajYK8UglQdydwEkJw2Lg5mzkIQ1HmWp0pRAwxyOY6X6w0FMT8qfL9N6YTCB4Ea/pEMnO6rLgIyZmZ+Rm6sWjIraTes5YQgIlpEMAOtUAVH51g3q1uWF6IVVx3Hkk2z4HkvOs4JGobCf6BCq+fSVLG1XoMDpFiynBrh4oUeKIDlJhV21nq7JXQEtSL5VmxETf/7mMmGV4R9uZfP/WE0DYwqip74Y3NpUdKYWx4vTORN9gLlqBcz0k="
    # CI_DEPLOY_PASSWORD
    - secure: "HFfzO8oID3XaMkrTtTXFFvmDpFebKwj3TgJG1jt2SxjlQs6kWVqz4L10sFjGyFhHl3nc6ADUyuksUtFznEhtEZ5sE8YBAotBox/iDH94A4tOBTWqKm6q/MA28Ge2x6kiq4Md2GSaSSspmEYn7heB0L7phIOycv6xU+D6fX57/1aX6ky2UAjqEtX+dpqmh+dtZk/BUxCKATEQ3ezz3oaiUa0F7Udbq9hZ61ZAEHlSsyitjPOQkglXX3pIsw1cDX3lm7OlIrajVAYnGEp1UZGBn87oG1kuH7foSk7v7rgveDMsUmxrraD+//UUrc/ymLIN+AljFwNnLNTgBSZRbUSq6F2yQCIWq0TZwyRJq1Pf2bQ40AYo5ME/bQ8dC+vfVIpnCnjCjlrx8xMv3lU6ebwYyWs1dOLdm/6K0kpu3wxLfb6XBYE9amyttdk+U5sEn8N04uRUND2uDmxqUpdIDej+vlxSReBZwTMjLGmcDu4cri3Z6SvoqmhjvHcjHO0JwM8DqcGIAffIAGSfcz1X48JibHNfVIWKcLo6dBM4Juhuz5DbLh8mccRg3j+KBp+Xy8FSMSWkxvOb06ErBU51wsTYCY17lAZOCq2l8sNkti7/slS0ltOmki5M5JPRggwrEKksyemrcrfuwHyqquadn2z9znXWWq9jaDTlTA7Z4lz9b20="
